### ISSUE TITLE
Feature request: Draconic staff of sponge.

### ISSUE THREAD

**Issue by NJM1564** [HFrajacomo/Draconic-Revolution#42]
https://github.com/HFrajacomo/Draconic-Revolution/issues/41
"Sometimes when using Ultimine with it it ate hunks of the ocian. Voiding them leaving holes that [didn't collapse] on there own. Having to fill them in to trigger a block update."

Is there anyway we can get this to happen on purpuse. A water clearing mode/draconic sponge modual would be super helpful. Took to much time to clear the aria under water that I wanted to use. And sponges do nothing to an ocean biom.

**Comment by HFrajacomo** [comment]
Hey man, I understand the usefulness that something like a Draconic Staff would have mechanics-wise in it, but I think there's just a little issue with your suggestion: you are probably talking about a different game.
